runtime: python27
api_version: 1
threadsafe: distributed
handlers:
- url: /.*
  script: connect.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

cloud_sql_instances: "s3488797-cc2019:australia-southeast1:sql-storage"
