runtime: python27
entrypoint: gunicorn -b :$PORT main:app
api_version: 1
threadsafe: distributed
handlers:
- url: /.*
  script: connect.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: flask
  version: 0.12
- name: ssl
  version: 2.7.11

runtime_config:
 python_version: 2.7

beta_settings:
  cloud_sql_instances: "s3488797-cc2019:australia-southeast1:sql-storage"
