import os
SECRET_KEY = 'Cloud2019'
DATA_BACKEND = 'cloudsql'
PROJECT_ID = 's3488797-cc2019'

CLOUDSQL_USER = 'root'
CLOUDSQL_PASSWORD = 'Cloud2019'
CLOUDSQL_DATABASE = 'spotify_project'
CLOUDSQL_CONNECTION_NAME = 's3488797-cc2019:australia-southeast1:sql-storage'
SQLALCHEMY_TRACK_MODIFICATIONS = False

LOCAL_URI_STRING = 'mysql+pymysql://'+CLOUDSQL_USER+':'+CLOUDSQL_PASSWORD+'@127.0.0.1:3306/'+CLOUDSQL_DATABASE
LOCAL_SQLALCHEMY_DATABASE_URI = (LOCAL_URI_STRING).format(
        user=CLOUDSQL_USER, password=CLOUDSQL_PASSWORD,
        database=CLOUDSQL_DATABASE)

if (os.environ.get('APPLICATION_ID') == 'f~' + PROJECT_ID):
    LIVE_CONNECTION_ADDRESS = 'localhost'
else:
    LIVE_CONNECTION_ADDRESS = 'https://' + PROJECT_ID + '.appspot.com/'

# When running on App Engine a unix socket is used to connect to the cloudsql
# instance.
LIVE_URI_STRING = 'mysql+pymysql://'+CLOUDSQL_USER+':'+CLOUDSQL_PASSWORD+'@'+LIVE_CONNECTION_ADDRESS+'/'+CLOUDSQL_DATABASE+'?unix_socket=/'+DATA_BACKEND+'/'+CLOUDSQL_CONNECTION_NAME
LIVE_SQLALCHEMY_DATABASE_URI = (LIVE_URI_STRING).format(
        user=CLOUDSQL_USER, password=CLOUDSQL_PASSWORD,
        database=CLOUDSQL_DATABASE, connection_name=CLOUDSQL_CONNECTION_NAME)

if os.environ.get('GAE_ENV'):
    SQLALCHEMY_DATABASE_URI = LIVE_SQLALCHEMY_DATABASE_URI
else:
    SQLALCHEMY_DATABASE_URI = LOCAL_SQLALCHEMY_DATABASE_URI
